name: DevSecOps Security Pipeline

on:
  push:
    branches: [main]

jobs:
  sca-scan:
    name: "Run Trivy SCA"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'json'
          output: 'trivy-fs-report.json'
          severity: 'CRITICAL,HIGH'

  sast-scan:
    name: "Run Semgrep SAST"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Semgrep
        run: |
          python3 -m pip install semgrep
          semgrep --config auto ./juice-shop --json -o semgrep-report.json || true

  build-and-scan:
    name: "Build Docker Image & Scan"
    runs-on: ubuntu-latest
    needs: [sca-scan, sast-scan]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t devsecops-app:${{ github.sha }} .

      - name: Scan built image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'devsecops-app:${{ github.sha }}'
          format: 'json'
          output: 'trivy-image-report.json'
          severity: 'HIGH,CRITICAL'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docker Hub
        run: |
          docker tag devsecops-app:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/devsecops-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devsecops-app:latest
